apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: YSQL
    uid: ysql
    type: postgres
    access: proxy
    url: yb-node1:5433
    database: yugabyte
    user: yugabyte
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1100
      timescaledb: false
    secureJsonData:
      password: yugabyte
